"""collection.monitor_scope — resolve the 24/7 monitor's market scope (READ-ONLY, free).

The monitor watches a config-declared slice of Kalshi (config/monitor.yaml `scope:` —
series prefixes like KXHIGH/KXLOW, whole categories like Mentions, explicit tickers).
This module turns that declaration into concrete open markets, hourly:

  1. one throttled `GET /series` for the full series list with categories (a series'
     category is the only place "Mentions" lives; the /markets listing does not carry it);
  2. select the scoped SERIES from that list (prefix / category / explicit), then one
     bounded `GET /markets?series_ticker=X&status=open` per scoped series. Per-series, NOT
     a universe sweep: measured 2026-08-25, `/markets?status=open` is dominated by ~100k
     KXMVECROSSCATEGORY parlay-shard markets, so whole-universe pagination never reaches
     the scoped series within any sane call cap. ~520 scoped series x 1 page is ~2 min of
     throttled calls; a series that overflows its page cap is counted `truncated`;
  3. keep per-market lifecycle metadata (open_time / close_time — the labels Layer 2's
     horizons need) and write one `monitor_scope.v1` line per in-scope market to
     `tape/monitor_markets/dt=YYYY-MM-DD.jsonl`;
  4. select the ws_depth subscription set: sort by 24h volume desc then soonest close,
     cap at `selection.max_tickers` (honest `truncated` + counted drops), and rewrite
     `config/ws_depth_tickers.txt` ATOMICALLY only when the set changed.

The caller (ops/vps/kalshi-headless-scope.sh) restarts the ws_depth daemon when this
module reports `tickers_changed: true` — the daemon itself stays a dumb subscriber.

House contract: canonical JSONL, bitemporal `captured_at`+`capture_id`, `raw_sha256` over
the exact bytes received, counted refusals (`n_out_of_scope`, `n_dropped_by_cap`), rate
limiting + pagination caps via the shared throttled client. Prices are NOT captured here
(ws_depth and universe_sweep own prices); scope lines carry no price and no price tag.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from core.canonical import canonical_json, sha256_hex
from core.io import REPO_ROOT
from core.kalshi_fields import parse_kalshi_numeric as _to_float
from core import monitor_config

SCHEMA_VERSION = "monitor_scope.v1"
TAPE = REPO_ROOT / "tape" / "monitor_markets"
TICKERS_PATH = REPO_ROOT / "config" / "ws_depth_tickers.txt"

# Per-series pagination bound. One page of 200 covers every observed weather/mention
# series; a series that still has a cursor after MAX_PAGES_PER_SERIES is counted in
# `n_series_truncated` and fails completeness_ok — never silently clipped.
PAGE_LIMIT = 200
MAX_PAGES_PER_SERIES = 3

_TICKERS_HEADER = """\
# ws_depth_tickers.txt — ws_depth WS subscription set.
# GENERATED by collection/monitor_scope.py from config/monitor.yaml `scope:` — edit THAT
# file to change what the monitor watches; hand edits here are overwritten hourly.
"""


def fetch_series_categories(client) -> Tuple[Dict[str, str], str]:
    """One `GET /series` -> {series_ticker: category}, plus the sha256 of the raw bytes."""
    text = client.get_text("/series")
    doc = json.loads(text)
    cats = {s.get("ticker"): (s.get("category") or "") for s in doc.get("series") or []
            if s.get("ticker")}
    return cats, sha256_hex(text.encode("utf-8"))


def in_scope(series: Optional[str], category: str, scope: Dict[str, Any]) -> bool:
    if not series:
        return False
    return (any(series.startswith(p) for p in scope["series_prefixes"])
            or (category and category in scope["categories"])
            or series in scope["series_tickers"])


def scoped_series(cats: Dict[str, str], scope: Dict[str, Any]) -> List[str]:
    """Every known series the scope declaration selects, plus explicit tickers the /series
    listing may not carry (they still get a per-series markets call)."""
    selected = [s for s, c in cats.items() if in_scope(s, c, scope)]
    selected += [s for s in scope["series_tickers"] if s not in cats]
    return sorted(set(selected))


def fetch_series_open_markets(client, series: str) -> Tuple[List[Dict[str, Any]],
                                                            List[str], bool]:
    """Bounded `GET /markets?series_ticker=<series>&status=open`. Returns
    (markets, raw_pages, truncated)."""
    markets: List[Dict[str, Any]] = []
    raw_pages: List[str] = []
    cursor: Optional[str] = None
    for _ in range(MAX_PAGES_PER_SERIES):
        params: Dict[str, Any] = {"series_ticker": series, "status": "open",
                                  "limit": PAGE_LIMIT}
        if cursor:
            params["cursor"] = cursor
        text = client.get_text("/markets", **params)
        raw_pages.append(text)
        j = json.loads(text)
        items = j.get("markets") or []
        markets.extend(items)
        cursor = j.get("cursor")
        if not cursor or not items:
            return markets, raw_pages, False
    return markets, raw_pages, True


def select_tickers(records: List[Dict[str, Any]], max_tickers: int
                   ) -> Tuple[List[str], int]:
    """Priority order: 24h volume desc, then soonest close, then ticker (deterministic).
    Returns (selected tickers, n_dropped_by_cap)."""
    def key(r):
        return (-(r.get("volume_24h") or 0.0), r.get("close_time") or "9999", r["ticker"])
    ranked = sorted(records, key=key)
    selected = [r["ticker"] for r in ranked[:max_tickers]]
    return selected, max(0, len(ranked) - max_tickers)


def write_tickers_file(tickers: List[str], path: Path = TICKERS_PATH) -> bool:
    """Atomic rewrite; returns True iff the SET of tickers changed (order-insensitive, so
    volume-rank churn alone never triggers a daemon restart)."""
    try:
        old = {ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
               if ln.strip() and not ln.strip().startswith("#")}
    except FileNotFoundError:
        old = set()
    if old == set(tickers):
        return False
    tmp = path.with_suffix(".txt.tmp")
    tmp.write_text(_TICKERS_HEADER + "".join(t + "\n" for t in sorted(tickers)),
                   encoding="utf-8")
    tmp.replace(path)
    return True


def _record(m: Dict[str, Any], series: str, category: str, selected: bool,
            captured_at: str, capture_id: str) -> Dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "capture_id": capture_id,
        "captured_at": captured_at,
        "venue": "kalshi",
        "ticker": m.get("ticker"),
        "event_ticker": m.get("event_ticker") or None,
        "series": series,
        "category": category or None,
        "title": m.get("title"),
        "status": m.get("status"),
        "open_time": m.get("open_time"),
        "close_time": m.get("close_time"),
        "expected_expiration_time": m.get("expected_expiration_time"),
        "volume_24h": _to_float(m.get("volume_24h_fp")),
        "open_interest": _to_float(m.get("open_interest_fp")),
        "ws_selected": selected,
    }


def run(client=None, store: Optional[Path] = None, tickers_path: Path = TICKERS_PATH,
        config: Optional[Dict[str, Any]] = None, min_interval: float = 0.25
        ) -> Dict[str, Any]:
    cfg = config if config is not None else monitor_config.load()
    scope, selection = cfg["scope"], cfg["selection"]
    if client is None:
        from validation.v3_market import Kalshi, _load_venue_cfg
        client = Kalshi(_load_venue_cfg()["api_base"], min_interval=min_interval)
    store = Path(store) if store is not None else TAPE

    now = datetime.now(timezone.utc)
    captured_at, capture_id = now.isoformat(), now.strftime("%Y%m%dT%H%M%S%fZ")

    cats, series_sha = fetch_series_categories(client)
    series_list = scoped_series(cats, scope)

    pre: List[Dict[str, Any]] = []
    raw_pages: List[str] = []
    n_calls = 1                     # the /series call
    n_series_truncated = 0
    n_series_with_open = 0
    for series in series_list:
        markets, pages, truncated = fetch_series_open_markets(client, series)
        raw_pages.extend(pages)
        n_calls += len(pages)
        n_series_truncated += 1 if truncated else 0
        n_series_with_open += 1 if markets else 0
        category = cats.get(series, "")
        pre.extend(_record(m, series, category, False, captured_at, capture_id)
                   for m in markets)
    tickers, n_dropped_by_cap = select_tickers(pre, int(selection["max_tickers"]))
    chosen = set(tickers)
    lines = []
    for rec in pre:
        rec["ws_selected"] = rec["ticker"] in chosen
        lines.append(canonical_json(rec))

    store.mkdir(parents=True, exist_ok=True)
    day = now.strftime("%Y-%m-%d")
    with open(store / f"dt={day}.jsonl", "a", encoding="utf-8") as fh:
        fh.write("".join(ln + "\n" for ln in lines))

    tickers_changed = write_tickers_file(tickers, tickers_path)

    summary = {
        "schema_version": "monitor_scope.summary.v1",
        "capture_id": capture_id, "captured_at": captured_at,
        "n_series_scoped": len(series_list), "n_series_with_open": n_series_with_open,
        "n_series_truncated": n_series_truncated, "n_in_scope": len(pre),
        "n_ws_selected": len(tickers), "n_dropped_by_cap": n_dropped_by_cap,
        "tickers_changed": tickers_changed, "n_calls": n_calls,
        "series_raw_sha256": series_sha, "pages_sha256": sha256_hex(
            "".join(raw_pages).encode("utf-8")),
        # a truncated series means scope may be silently missing markets — FAIL loud
        "completeness_ok": n_series_truncated == 0,
    }
    with open(store / f"dt={day}.jsonl", "a", encoding="utf-8") as fh:
        fh.write(canonical_json(summary) + "\n")
    print(f"[monitor_scope] {canonical_json(summary)}", flush=True)
    return summary


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Resolve monitor market scope (read-only).")
    ap.add_argument("--min-interval", type=float, default=0.25)
    args = ap.parse_args(argv)
    summary = run(min_interval=args.min_interval)
    return 0 if summary.get("completeness_ok") else 1


if __name__ == "__main__":
    sys.exit(main())
